server {
    listen       80;
    server_name  localhost;

    location /api/ {
        proxy_pass $API_URL/;
    }

    location /env.js {
  	default_type text/javascript;
  	return 200 '
window.env = {
  API_URL: "/api",
  GOOGLE_CLIENT_ID: "$GOOGLE_CLIENT_ID"
}';
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

}

